# Generated by Django 5.2.3 on 2025-07-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileTree',
            fields=[
                ('path_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('path', models.TextField()),
                ('path_hash', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('parent_path', models.TextField(blank=True, null=True)),
                ('parent_path_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.CharField(choices=[('file', 'File'), ('directory', 'Directory')], max_length=10)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'file_tree_list',
                'indexes': [models.Index(fields=['path_hash'], name='file_tree_l_path_ha_17536d_idx')],
            },
        ),
    ]
